services:
    php:
        build:
            context: .
            dockerfile: docker/Dockerfile.php82
        volumes:
            - .:/var/www/html
        environment:
            XDEBUG_MODE: ${XDEBUG_MODE:-develop,debug}
            XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST:-host.docker.internal}
            XDEBUG_CLIENT_PORT: ${XDEBUG_CLIENT_PORT:-9090}
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=andanteproject-shared-query-builder}
            XDEBUG_START_WITH_REQUEST: ${XDEBUG_START_WITH_REQUEST:-yes}
